import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css?v=2";
import { Toaster } from "sonner";
import { cn } from "@/utils";
import Providers from "@/providers";
import NextTopLoader from "nextjs-toploader";
import Header from "@/components/layouts/header";
import { ReactNode } from "react";
import { getUserFromCookie } from "@/lib/server-utils/cookie";

const font = Be_Vietnam_Pro({
  variable: "--font-sans",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: Readonly<ReactNode>;
}

export default async function RootLayout({ children }: Readonly<LayoutProps>) {
  const user = await getUserFromCookie();

  return (
    <html lang="en">
      <head>
        <meta name="color-scheme" content="light dark" />
      </head>
      <body className={cn(font.variable, "antialiased")}>
        <NextTopLoader
          color="#000000"
          initialPosition={0.08}
          crawlSpeed={200}
          height={2}
          crawl={true}
          showSpinner={false}
          easing="ease"
          speed={200}
        />
        <Toaster
          richColors
          position="bottom-left"
          theme="system"
          closeButton={true}
          duration={5000}
        />
        <Providers>
          <Header user={user} />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
