import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css?v=2";
import { Toaster } from "react-hot-toast";
import { cn } from "@/utils";
import ProgressBar from "@/components/common/progress-bar";
import Providers from "@/providers";

const font = Be_Vietnam_Pro({
  variable: "--font-sans",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="color-scheme" content="light dark" />
      </head>
      <body className={cn(font.variable, "antialiased")}>
        <ProgressBar />
        <Toaster
          position="bottom-left"
          gutter={16}
          toastOptions={{ duration: 5000 }}
        />
        <Providers children={children} />
      </body>
    </html>
  );
}
